// Generated by gencpp from file add_markers/PositionActionRequest.msg
// DO NOT EDIT!


#ifndef ADD_MARKERS_MESSAGE_POSITIONACTIONREQUEST_H
#define ADD_MARKERS_MESSAGE_POSITIONACTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace add_markers
{
template <class ContainerAllocator>
struct PositionActionRequest_
{
  typedef PositionActionRequest_<ContainerAllocator> Type;

  PositionActionRequest_()
    : action(0)  {
    }
  PositionActionRequest_(const ContainerAllocator& _alloc)
    : action(0)  {
  (void)_alloc;
    }



   typedef uint32_t _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::add_markers::PositionActionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::add_markers::PositionActionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PositionActionRequest_

typedef ::add_markers::PositionActionRequest_<std::allocator<void> > PositionActionRequest;

typedef boost::shared_ptr< ::add_markers::PositionActionRequest > PositionActionRequestPtr;
typedef boost::shared_ptr< ::add_markers::PositionActionRequest const> PositionActionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::add_markers::PositionActionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::add_markers::PositionActionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace add_markers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::add_markers::PositionActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::add_markers::PositionActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::add_markers::PositionActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::add_markers::PositionActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_markers::PositionActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_markers::PositionActionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::add_markers::PositionActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5565ed6f692a31cd1607bc66d8256ac3";
  }

  static const char* value(const ::add_markers::PositionActionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5565ed6f692a31cdULL;
  static const uint64_t static_value2 = 0x1607bc66d8256ac3ULL;
};

template<class ContainerAllocator>
struct DataType< ::add_markers::PositionActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "add_markers/PositionActionRequest";
  }

  static const char* value(const ::add_markers::PositionActionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::add_markers::PositionActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 action\n\
";
  }

  static const char* value(const ::add_markers::PositionActionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::add_markers::PositionActionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionActionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::add_markers::PositionActionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::add_markers::PositionActionRequest_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADD_MARKERS_MESSAGE_POSITIONACTIONREQUEST_H
