// Generated by gencpp from file add_markers/PositionActionResponse.msg
// DO NOT EDIT!


#ifndef ADD_MARKERS_MESSAGE_POSITIONACTIONRESPONSE_H
#define ADD_MARKERS_MESSAGE_POSITIONACTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace add_markers
{
template <class ContainerAllocator>
struct PositionActionResponse_
{
  typedef PositionActionResponse_<ContainerAllocator> Type;

  PositionActionResponse_()
    : msg_feedback()  {
    }
  PositionActionResponse_(const ContainerAllocator& _alloc)
    : msg_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_feedback_type;
  _msg_feedback_type msg_feedback;





  typedef boost::shared_ptr< ::add_markers::PositionActionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::add_markers::PositionActionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PositionActionResponse_

typedef ::add_markers::PositionActionResponse_<std::allocator<void> > PositionActionResponse;

typedef boost::shared_ptr< ::add_markers::PositionActionResponse > PositionActionResponsePtr;
typedef boost::shared_ptr< ::add_markers::PositionActionResponse const> PositionActionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::add_markers::PositionActionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::add_markers::PositionActionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace add_markers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::add_markers::PositionActionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::add_markers::PositionActionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::add_markers::PositionActionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::add_markers::PositionActionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_markers::PositionActionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_markers::PositionActionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::add_markers::PositionActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2897a4bc4d7ca330e430870cfdee7314";
  }

  static const char* value(const ::add_markers::PositionActionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2897a4bc4d7ca330ULL;
  static const uint64_t static_value2 = 0xe430870cfdee7314ULL;
};

template<class ContainerAllocator>
struct DataType< ::add_markers::PositionActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "add_markers/PositionActionResponse";
  }

  static const char* value(const ::add_markers::PositionActionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::add_markers::PositionActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string msg_feedback\n\
\n\
";
  }

  static const char* value(const ::add_markers::PositionActionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::add_markers::PositionActionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionActionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::add_markers::PositionActionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::add_markers::PositionActionResponse_<ContainerAllocator>& v)
  {
    s << indent << "msg_feedback: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADD_MARKERS_MESSAGE_POSITIONACTIONRESPONSE_H
